# Tomcat
#
# VERSION 4

FROM       docker.xlands-inc.com/baoyu/java8
MAINTAINER djluo <dj.luo@baoyugame.com>

ENV  TomcatVer 8.0.32
COPY ./apache-tomcat-${TomcatVer} /apache-tomcat-${TomcatVer}

COPY ./conf/server.xml.8       /tomcat/conf/server.xml
COPY ./conf/logging.properties /tomcat/conf/logging.properties

RUN chmod 644 /apache-tomcat-${TomcatVer}/conf/* \
    && sed -i 's/\(.*\)\(...$LOGGING_CONFIG...\)\(.*\)$JAVA_OPTS\(.*\)/\1$JAVA_OPTS \2\3\4/' \
    /apache-tomcat-${TomcatVer}/bin/catalina.sh

COPY ./cmd.sh        /tomcat/cmd.sh
COPY ./gzip.sh       /tomcat/gzip.sh
COPY ./entrypoint.pl /entrypoint.pl

ENTRYPOINT ["/entrypoint.pl"]
CMD        ["/tomcat/cmd.sh"]
